### ISSUE TITLE
:pray: Feature Request > Please add csv to your output options :bar_chart: 

### ISSUE THREAD

**Issue by adriens** [hugovk/norwegianblue#110]
# :grey_question: Context

Currently,

```
❯ eol --version
eol 0.9.0 (Python 3.10.6)
```

The available output options are 

```
-f {html,json,markdown,rst,tsv}, --format {html,json,markdown,rst,tsv}
```

But most ETL (and other tools) support `csv` as input format... and often make the load of `csv` the default mode.

# :pray:  Feature request

Please add `csv` output option, respecting [`rfc4180`](https://www.rfc-editor.org/rfc/rfc4180)

For example, the following command : 

```
norwegianblue spring-framework -f csv
```

Would return : 

```
"cycle","release","latest","latest release","support","eol"
"5.3","2020-10-27","5.3.23","2022-09-15","True","False"
"5.2","2019-09-30","5.2.22","2022-05-11","True","2021-12-31"
"5.1","2018-09-21","5.1.20","2020-12-09","False","2020-12-09"
"5.0","2017-09-28","5.0.20","2020-12-09","False","2020-12-09"
"4.3","2016-06-10","4.3.30","2020-12-09","False","2020-12-31"
"3.2","2012-12-13","3.2.18","2016-12-21","False","2016-12-31"
```

Thank you in advance and thanks a lot for your tool :clap:

**Comment by hugovk** [comment]
Thanks for the request. CSV can be added easily enough, although there's already TSV, does that work for you?

**Comment by adriens** [comment]
`csv` has better support or many platforms. And for example, if well formated, **it can also be previewed on Github** which is very useful. :smile_cat: 
Also, for datascience `csv` is more comonly used. :thought_balloon:

**Comment by hugovk** [comment]
Sure, please see PR https://github.com/hugovk/norwegianblue/pull/111.

**Comment by adriens** [comment]
Jus got it

![image](https://user-images.githubusercontent.com/5235127/200283425-1ec21a11-6e9d-471c-8af7-6017443b4ed7.png)

**Comment by adriens** [comment]
Thanks a lot for your kind support.

I'll write a dedicated blog post to end-of-life.date and the tooling around it.... and of course the `csv`  part :smiley:
