### ISSUE TITLE
:pray: Feature Request > --web (-w) option

### ISSUE THREAD

**Issue by adriens** [hugovk/norwegianblue#141]
# :grey_question: About

Actually `eol` and `endoflife.date` User experiences are quite splitted in two disinct worlds. But sometimes, it could be ceonvenient to switch from `cli` to `GUI`.

For example [`gh`](https://cli.github.com/) has [this option](https://cli.github.com/manual/gh_repo):

```shell
gh repo view --web
```

# :bulb:  Feature request

Ad the `--web` / `-w` option which : 

- Opens the user's default web browser on product's page on `endoflife.date` if a single product is provided
- Open n browsers for each product provided on the cli

**Comment by adriens** [comment]
:star_struck: when will you release a new version :grey_question:

**Comment by hugovk** [comment]
Will release when https://github.com/hugovk/norwegianblue/pull/143 is merged.
