### ISSUE TITLE
:pray:  User Experience on cli > left alignement of "cycle"

### ISSUE THREAD

**Issue by adriens** [hugovk/norwegianblue#154]
# :grey_question: About

Currently, on the `cli`, `cycle` is centered:

<pre>┌────────────────────────────────────────────────────────────────
│                                                                
├────────┬────────────┬──────────┬────────────────┬────────────┬─
│ <b>cycle</b>  │  <b>release</b>   │  <b>latest</b>  │ <b>latest release</b> │  <b>support</b>   │ 
├────────┼────────────┼──────────┼────────────────┼────────────┼─
│ 20 LTS │ 2023-04-18 │  20.2.0  │   2023-05-16   │ <font color="#4E9A06">2024-10-22</font> │ 
│   19   │ 2022-10-18 │  19.9.0  │   2023-04-10   │ <font color="#CC0000">2023-04-01</font> │ 
│ 18 LTS │ 2022-04-19 │ 18.16.0  │   2023-04-12   │ <font color="#C4A000">2023-10-18</font> │ 
│   17   │ 2021-10-19 │  17.9.1  │   2022-06-01   │ <font color="#CC0000">2022-04-01</font> │ 
│ 16 LTS │ 2021-04-20 │ 16.20.0  │   2023-03-29   │ <font color="#CC0000">2022-10-18</font> │ 
│   15   │ 2020-10-20 │ 15.14.0  │   2021-04-06   │ <font color="#CC0000">2021-04-01</font> │ 
│ 14 LTS │ 2020-04-21 │ 14.21.3  │   2023-02-16   │ <font color="#CC0000">2021-10-19</font> │ 
│   13   │ 2019-10-22 │ 13.14.0  │   2020-04-29   │ <font color="#CC0000">2020-04-01</font> │ 
</pre>

... which makes it not optimal to read (my own point of view).

But when we export as `markdown`, it is left justified.... which make things (my pov) very comfortable to read:

![image](https://github.com/hugovk/norwegianblue/assets/5235127/5f8b375f-a134-49da-a744-1c40e3c8403a)

# :pray: Feature request

- Left align `cycle` on the `cli` output

**Comment by hugovk** [comment]
Thanks, this is actually a bug and will be fixed by https://github.com/hugovk/norwegianblue/pull/155.

**Comment by adriens** [comment]
:ok_man: 
![image](https://github.com/hugovk/norwegianblue/assets/5235127/e45963e3-9b56-462b-9037-2606a084c06a)
