### ISSUE TITLE
:lady_beetle: No link for consul/quarkus :grey_question: 

### ISSUE THREAD

**Issue by adriens** [hugovk/norwegianblue#159]
# :grey_question: About

When getting `consul` from `eol` I get this : 

<pre><font color="#5FD700">❯</font> eol consul
┌───────┬────────────┬─────────┬────────────────┬────────────┐
│ <b>cycle</b> │  <b>release</b>   │ <b>latest</b>  │ <b>latest release</b> │    <b>eol</b>     │
├───────┼────────────┼─────────┼────────────────┼────────────┤
│ 1.15  │ 2023-02-23 │ 1.15.3  │   2023-06-01   │   <font color="#4E9A06">False</font>    │
│ 1.14  │ 2022-11-15 │ 1.14.7  │   2023-05-15   │   <font color="#4E9A06">False</font>    │
│ 1.13  │ 2022-08-09 │ 1.13.8  │   2023-05-15   │   <font color="#4E9A06">False</font>    │
│ 1.12  │ 2022-04-19 │ 1.12.9  │   2023-01-26   │ <font color="#CC0000">2023-02-23</font> │
│ 1.11  │ 2021-12-14 │ 1.11.11 │   2022-10-19   │ <font color="#CC0000">2022-11-15</font> │
│ 1.10  │ 2021-06-22 │ 1.10.12 │   2022-07-13   │ <font color="#CC0000">2022-08-09</font> │
│ 1.9   │ 2020-11-24 │ 1.9.17  │   2022-04-14   │    <font color="#CC0000">True</font>    │
│ 1.8   │ 2020-06-18 │ 1.8.19  │   2021-12-15   │    <font color="#CC0000">True</font>    │
└───────┴────────────┴─────────┴────────────────┴────────────┘
</pre>

... while I get this on https://endoflife.date/consul (see links are available): 

![image](https://github.com/hugovk/norwegianblue/assets/5235127/be9f2752-12ec-477b-a69c-7d6e03c4dde9)

# :tickets: Related issues

- https://github.com/endoflife-date/endoflife.date/pull/3033#pullrequestreview-1458937509

**Comment by hugovk** [comment]
Yes, I'd noticed the links were no longer available. Here's an old `eol ubuntu` showing a link column: https://github.com/hugovk/norwegianblue/pull/82

And now:

<details>
<summary>Details</summary>

```console
❯ eol ubuntu -v
Human URL:	https://endoflife.date/ubuntu
API URL:	https://endoflife.date/api/ubuntu.json
Source URL:	https://github.com/endoflife-date/endoflife.date/blob/master/products/ubuntu.md
Cache file:	/Users/hugo/Library/Caches/norwegianblue/2023-06-03-https-endoflife-date-api-ubuntu-json.json
Cache file exists

┌───────────┬───────────────────┬────────────┬─────────┬────────────────┬────────────┬────────────┬─────────────────┐
│   cycle   │      codename     │  release   │  latest │ latest release │  support   │    eol     │ extendedSupport │
├───────────┼───────────────────┼────────────┼─────────┼────────────────┼────────────┼────────────┼─────────────────┤
│   23.04   │   Lunar Lobster   │ 2023-04-20 │  23.04  │   2023-04-20   │ 2024-01-20 │ 2024-01-20 │      False      │
│   22.10   │    Kinetic Kudu   │ 2022-10-20 │  22.10  │   2022-10-20   │ 2023-07-20 │ 2023-07-20 │      False      │
│ 22.04 LTS │  Jammy Jellyfish  │ 2022-04-21 │ 22.04.2 │   2023-02-24   │ 2024-09-30 │ 2027-04-01 │    2032-04-09   │
│   21.10   │    Impish Indri   │ 2021-10-14 │  21.10  │   2021-10-14   │ 2022-07-14 │ 2022-07-14 │      False      │
│   21.04   │   Hirsute Hippo   │ 2021-04-22 │  21.04  │   2021-04-22   │ 2022-01-20 │ 2022-01-20 │      False      │
│   20.10   │   Groovy Gorilla  │ 2020-10-22 │  20.10  │   2020-10-22   │ 2021-07-22 │ 2021-07-22 │      False      │
│ 20.04 LTS │    Focal Fossa    │ 2020-04-23 │ 20.04.6 │   2023-03-23   │ 2022-10-01 │ 2025-04-02 │    2030-04-02   │
│   19.10   │    Eoan Ermine    │ 2019-10-17 │  19.10  │   2019-10-17   │ 2020-07-06 │ 2020-07-06 │      False      │
│   19.04   │    Disco Dingo    │ 2019-04-18 │  19.04  │   2019-04-18   │ 2020-01-23 │ 2020-01-23 │      False      │
│   18.10   │ Cosmic Cuttlefish │ 2018-10-18 │  18.10  │   2018-10-18   │ 2019-07-18 │ 2019-07-18 │      False      │
│ 18.04 LTS │   Bionic Beaver   │ 2018-04-26 │ 18.04.6 │   2021-09-17   │ 2023-05-31 │ 2023-05-31 │    2028-04-01   │
│   17.10   │  Artful Aardvark  │ 2017-10-19 │  17.10  │   2017-10-19   │ 2018-07-19 │ 2018-07-19 │      False      │
│   17.04   │    Zesty Zapus    │ 2017-04-13 │  17.04  │   2017-04-13   │ 2018-01-13 │ 2018-01-13 │      False      │
│ 16.04 LTS │    Xenial Xerus   │ 2016-04-21 │ 16.04.7 │   2020-08-13   │ 2021-04-02 │ 2021-04-02 │    2026-04-02   │
│   15.10   │   Wily Werewolf   │ 2015-10-22 │  15.10  │   2015-10-22   │ 2016-07-28 │ 2016-07-28 │      False      │
│   15.04   │    Vivid Vervet   │ 2015-04-23 │  15.04  │   2015-04-23   │ 2016-02-04 │ 2016-02-04 │      False      │
│   14.10   │   Utopic Unicorn  │ 2014-10-23 │  14.10  │   2014-10-23   │ 2015-07-23 │ 2015-07-23 │      False      │
│ 14.04 LTS │    Trusty Tahr    │ 2014-04-17 │ 14.04.6 │   2019-03-07   │ 2019-04-02 │ 2019-04-02 │    2024-04-02   │
│ 12.04 LTS │  Precise Pangolin │ 2012-04-26 │ 12.04.5 │   2014-08-08   │ 2017-04-28 │ 2017-04-28 │    2019-04-26   │
└───────────┴───────────────────┴────────────┴─────────┴────────────────┴────────────┴────────────┴─────────────────┘
```

</details>

Checking the API response, it no longer includes a link:

* https://endoflife.date/api/ubuntu.json

Looking at an archived response, it had a link:

* https://web.archive.org/web/20230129215437/https://endoflife.date/api/ubuntu.json

So an upstream https://endoflife.date/docs/api bug?

**Comment by adriens** [comment]
It'a a WIP, it will be fixed on API v1.... to be released soon.

**Comment by adriens** [comment]
It's API related
