### ISSUE TITLE
:gift: eol on tldr pages :nerd_face: 

### ISSUE THREAD

**Issue by adriens** [hugovk/norwegianblue#161]
# :grey_question: About

[`tldr` ](https://github.com/tldr-pages/tldr#what-is-tldr-pages) 

> "project is a collection of community-maintained help pages for command-line tools, that aims to be a simpler, more approachable complement to traditional [man pages](https://en.wikipedia.org/wiki/Man_page)."

# :gift_heart: Showtime

## :popcorn:  See it live

![ezgif-4-f9459d938e](https://github.com/hugovk/norwegianblue/assets/5235127/94a968bf-e158-4966-a874-afa66006ccee)

## :blue_book: As a book

![image](https://github.com/hugovk/norwegianblue/assets/5235127/cde19ab3-4413-45bd-9c0c-870b2f16967f)

# :bookmark_tabs: Ressources

- https://github.com/tldr-pages/tldr/pull/10380
- https://tldr.sh/
- https://tldr.sh/assets/tldr-book.pdf

**Comment by hugovk** [comment]
I use `tldr` as well, thanks!

**Comment by adriens** [comment]
I use eol on a daily basis, I'll do a short blog post about `tldr` and `eol` :muscle: 
It should help spread eol and endoflife.date :rocket:
