### ISSUE TITLE
Add format "python" (or similar name)

### ISSUE THREAD

**Issue by pauloxnet** [hugovk/norwegianblue#228]
If you want to use the result in python now you have to use the `JSON` format and loads it.

For example

```python
import json
import sysconfig

[v["support"] for v in json.loads(norwegianblue.norwegianblue(product="python", format="json")) if v["cycle"] == sysconfig.get_python_version()]
```

it will be useful to do something like 
```python
import sysconfig

[v["support"] for v in norwegianblue.norwegianblue(product="python", format="python") if v["cycle"] == sysconfig.get_python_version()]
```

I think it is doable avoiding using `json.dumps` like in https://github.com/hugovk/norwegianblue/blob/main/src/norwegianblue/__init__.py#L84

**Comment by hugovk** [comment]
Maybe something like #232? That uses `format = None`, I was thinking because we're not formatting it at all.

**Comment by pauloxnet** [comment]
It seems perfect 😊
